import { defineType, defineField } from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Ustawienia strony',
  type: 'document',
  icon: () => '⚙️',
  groups: [
    { name: 'pl', title: '🇵🇱 Polski', default: true },
    { name: 'en', title: '🇬🇧 English' },
    { name: 'contact', title: '📞 Kontakt' },
    { name: 'social', title: '🔗 Social' },
    { name: 'seo', title: '🔍 SEO / GEO' },
  ],
  fields: [
    /* ── PL fields ──────────────────────────────────────── */
    defineField({
      name: 'siteTitle',
      title: 'Tytuł strony',
      type: 'string',
      validation: (rule) => rule.required(),
      group: 'pl',
    }),
    defineField({
      name: 'siteDescription',
      title: 'Meta opis',
      type: 'text',
      rows: 3,
      group: 'pl',
    }),
    defineField({
      name: 'heroLabel',
      title: 'Hero — etykieta',
      type: 'string',
      description: 'Np. "Malarz · Kraków · Polska"',
      group: 'pl',
    }),
    defineField({
      name: 'heroHeadline',
      title: 'Hero — nagłówek (imię)',
      type: 'string',
      group: 'pl',
    }),
    defineField({
      name: 'heroHeadlineAccent',
      title: 'Hero — nagłówek (nazwisko, kursywa)',
      type: 'string',
      group: 'pl',
    }),
    defineField({
      name: 'heroTagline',
      title: 'Hero — podtytuł',
      type: 'text',
      rows: 2,
      group: 'pl',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero — obraz tła',
      type: 'image',
      options: { hotspot: true },
      group: 'pl',
    }),
    defineField({
      name: 'footerTagline',
      title: 'Stopka — motto',
      type: 'string',
      group: 'pl',
    }),
    defineField({
      name: 'privacyPolicy',
      title: 'Polityka prywatności',
      type: 'text',
      rows: 15,
      description: 'Pełna treść polityki prywatności (obsługuje entery)',
      group: 'pl',
    }),
    defineField({
      name: 'signatureTitle',
      title: 'Tytuł linku stopki (Title) - PL',
      description: 'Tekst dymku (tooltip) po najechaniu na podpis PRADOM w stopce.',
      type: 'string',
      group: 'pl',
    }),
    defineField({
      name: 'signatureAriaLabel',
      title: 'Opis dostępności stopki (Aria Label) - PL',
      description: 'Tekst dla czytników ekranu i SEO dla podpisu PRADOM w stopce.',
      type: 'string',
      group: 'pl',
    }),

    /* ── EN fields ──────────────────────────────────────── */
    defineField({
      name: 'siteTitle_en',
      title: 'Site title (EN)',
      type: 'string',
      group: 'en',
    }),
    defineField({
      name: 'siteDescription_en',
      title: 'Meta description (EN)',
      type: 'text',
      rows: 3,
      group: 'en',
    }),
    defineField({
      name: 'heroLabel_en',
      title: 'Hero — label (EN)',
      type: 'string',
      group: 'en',
    }),
    defineField({
      name: 'heroHeadline_en',
      title: 'Hero — headline first name (EN)',
      type: 'string',
      group: 'en',
    }),
    defineField({
      name: 'heroHeadlineAccent_en',
      title: 'Hero — headline surname italic (EN)',
      type: 'string',
      group: 'en',
    }),
    defineField({
      name: 'heroTagline_en',
      title: 'Hero — tagline (EN)',
      type: 'text',
      rows: 2,
      group: 'en',
    }),
    defineField({
      name: 'footerTagline_en',
      title: 'Footer tagline (EN)',
      type: 'string',
      group: 'en',
    }),
    defineField({
      name: 'privacyPolicy_en',
      title: 'Privacy policy (EN)',
      type: 'text',
      rows: 15,
      description: 'Full content of the privacy policy in English',
      group: 'en',
    }),
    defineField({
      name: 'signatureTitle_en',
      title: 'Signature tooltip title (Title) - EN',
      description: 'Tooltip text on hover for the PRADOM signature link in English.',
      type: 'string',
      group: 'en',
    }),
    defineField({
      name: 'signatureAriaLabel_en',
      title: 'Signature accessibility label (Aria Label) - EN',
      description: 'Screen reader and SEO text for the PRADOM signature link in English.',
      type: 'string',
      group: 'en',
    }),

    /* ── Contact (shared) ───────────────────────────────── */
    defineField({
      name: 'contactEmail',
      title: 'E-mail kontaktowy',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactPhone',
      title: 'Telefon',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactLocation',
      title: 'Lokalizacja',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'recaptchaEnabled',
      title: 'Włącz reCAPTCHA',
      description: 'Zabezpieczenie antyspamowe w formularzu kontaktowym.',
      type: 'boolean',
      initialValue: false,
      group: 'contact',
    }),
    defineField({
      name: 'recaptchaSiteKey',
      title: 'reCAPTCHA Site Key',
      description: 'Klucz publiczny witryny (v2 checkbox / invisible).',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'recaptchaSecretKey',
      title: 'reCAPTCHA Secret Key',
      description: 'Klucz tajny służący do weryfikacji po stronie serwera.',
      type: 'string',
      group: 'contact',
    }),

    /* ── Social (shared) ────────────────────────────────── */
    defineField({
      name: 'instagramUrl',
      title: 'Instagram URL',
      type: 'url',
      group: 'social',
    }),
    defineField({
      name: 'facebookUrl',
      title: 'Facebook URL',
      type: 'url',
      group: 'social',
    }),
    defineField({
      name: 'signatureUrl',
      title: 'Adres URL stopki (PRADOM)',
      description: 'Link do strony wykonawcy pod podpisem w stopce.',
      type: 'url',
      group: 'social',
    }),

    /* ── SEO / GEO ──────────────────────────────────────── */
    defineField({
      name: 'seoTitle',
      title: 'SEO Title (PL)',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'seoTitle_en',
      title: 'SEO Title (EN)',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO Description (PL)',
      type: 'text',
      rows: 3,
      group: 'seo',
    }),
    defineField({
      name: 'seoDescription_en',
      title: 'SEO Description (EN)',
      type: 'text',
      rows: 3,
      group: 'seo',
    }),
    defineField({
      name: 'seoWideDescription',
      title: 'SEO Wide Description (PL)',
      description: 'Długi, semantyczny tekst pozycjonujący wyświetlany nad stopką.',
      type: 'text',
      rows: 8,
      group: 'seo',
    }),
    defineField({
      name: 'seoWideDescription_en',
      title: 'SEO Wide Description (EN)',
      description: 'Long semantic positioning text displayed above the footer in English.',
      type: 'text',
      rows: 8,
      group: 'seo',
    }),
    defineField({
      name: 'entityType',
      title: 'Typ podmiotu (Entity Type)',
      description: 'Typ encji dla Schema.org, np. "Person", "Artist", "Painter".',
      type: 'string',
      initialValue: 'Person',
      group: 'seo',
    }),
    defineField({
      name: 'entityKeywords',
      title: 'Słowa kluczowe encji (PL)',
      description: 'Wykaz kluczowych pojęć powiązanych semantycznie, oddzielonych przecinkami.',
      type: 'text',
      rows: 2,
      group: 'seo',
    }),
    defineField({
      name: 'entityKeywords_en',
      title: 'Entity Keywords (EN)',
      description: 'Semantic key concepts separated by commas.',
      type: 'text',
      rows: 2,
      group: 'seo',
    }),
    defineField({
      name: 'entityStyles',
      title: 'Kierunki artystyczne / Style (PL)',
      description: 'Np. "Malarstwo abstrakcyjne, Ekspresjonizm".',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'entityStyles_en',
      title: 'Art styles / Movements (EN)',
      description: 'e.g. "Abstract Art, Expressionism".',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'wikidataUrl',
      title: 'Wikidata URL',
      type: 'url',
      group: 'seo',
    }),
    defineField({
      name: 'googleMapsUrl',
      title: 'Google Maps Business URL',
      type: 'url',
      group: 'seo',
    }),
    defineField({
      name: 'geoCoordinates',
      title: 'Współrzędne geograficzne',
      description: 'Szerokość i długość geograficzna, np. "50.0619, 19.9374".',
      type: 'string',
      group: 'seo',
    }),
  ],
  preview: {
    prepare() {
      return { title: 'Ustawienia strony' }
    },
  },
})
